import { createHash } from 'node:crypto';

export type ActivationIntentSource = 'public_website' | 'private_workspace_preview' | 'capsule_launcher' | 'operator_manual' | 'internal_case_zero';
export type ActivationIntentRoute = 'diagnostico' | 'start' | 'capsule' | 'capsule_pricing' | 'capsule_demo' | 'portal_vivo_demo' | 'manual_operator';
export type OperatingPath = 'local_byok' | 'starter_cloud' | 'pro_cloud' | 'enterprise_managed' | 'internal_case_zero';
export type RegionId = 'es_eu' | 'latam' | 'usa_uk' | 'other_review_required';
export type ActivationPackStatus = 'draft_received' | 'validation_failed' | 'review_required' | 'ready_for_operator_review' | 'blocked_invalid_scope' | 'blocked_sensitive_input' | 'blocked_missing_human_review' | 'blocked_byok_secret_material' | 'blocked_region_assumption' | 'blocked_unsupported_plan' | 'blocked_quarantined_route' | 'freeze_candidate_ready';
export type ByokReadinessStatus = 'not_requested' | 'requested_review_required' | 'pending_operator_setup' | 'blocked_secret_material_included' | 'blocked_plan_not_allowed' | 'ready_reference_only';
export type ChecklistStatus = 'pending' | 'passed' | 'warning' | 'blocked' | 'not_applicable';
export type ChecklistOwner = 'customer' | 'transformia_operator' | 'runtime' | 'launcher' | 'web';

export interface ActivationIntent { intentId: string; source: ActivationIntentSource; sourceRoute: ActivationIntentRoute; requestedAt: string; locale: string; regionId: RegionId; operatingPath: OperatingPath; selectedPlanCode: string; trialRequested: boolean; requestedTemplate: string; businessKind: string; organizationDraftRef: string; workspaceDraftRef: string; contactRef: string; notesPublicSafe: string; publicSafe: true; }
export interface OrganizationWorkspaceDraft { organizationDraftId: string; workspaceDraftId: string; organizationDisplayName: string; workspaceDisplayName: string; workspaceKind: string; locale: string; regionId: RegionId; publicSafe: true; }
export interface PlanTrialDraft { planCode: string; planDisplayName: string; trialRequested: boolean; trialState: 'not_requested' | 'trial_review_required'; commercialReviewRequired: true; automaticPurchaseFlow: false; instantProvisioning: false; publicSafe: true; }
export interface ByokReadinessDraft { byokRequested: boolean; providerKinds: string[]; secretMaterialIncluded: false; readinessStatus: ByokReadinessStatus; publicSafe: true; }
export interface CommissioningChecklistItem { itemId: string; label: string; status: ChecklistStatus; blocker: boolean; evidenceRef: string; owner: ChecklistOwner; publicSafe: true; }
export interface ValidationReport { ok: boolean; status: ActivationPackStatus; blockers: string[]; warnings: string[]; checkedInvariants: string[]; generatedFiles: string[]; checksum: string; publicSafe: true; }
export interface SaaSActivationPack { activationPackId: string; intent: ActivationIntent; organizationWorkspaceDraft: OrganizationWorkspaceDraft; planTrialDraft: PlanTrialDraft; byokReadinessDraft: ByokReadinessDraft; commissioningChecklist: CommissioningChecklistItem[]; humanReviewRequired: true; readyForCommissioning: boolean; readyForGoLive: false; publicSafeSummary: Record<string, unknown>; validationReport: ValidationReport; fingerprint: string; generatedAt: string; publicSafe: true; }
export interface FreezeCandidateSummary { version: 'v0.9'; capability: 'SaaS Activation Pack Handoff'; status: 'freeze_candidate_ready' | 'freeze_blocked'; requiredExternalEvidence: ('web_w01_w05' | 'runtime_b01_b05' | 'launcher_l01')[]; launcherEvidenceRefs: string[]; blockers: string[]; warnings: string[]; publicSafe: true; }

export const ALLOWED_ACTIVATION_ROUTES = ['diagnostico','start','capsule','capsule_pricing','capsule_demo','portal_vivo_demo','manual_operator'] as const;
export const QUARANTINED_WEB_ROUTES = ['/case-zero','/pilot','/cockpit','/connectors','/private','/demo/cockpit','/demo/flujo','/portal-vivo'] as const;
export const ACTIVATION_PACK_FILENAMES = ['activation-intent.public.json','organization-workspace-draft.public.json','plan-trial-draft.public.json','byok-readiness.public.json','commissioning-checklist.public.json','activation-pack.public.json','validation-report.public.json','v0.9-freeze-candidate.public.json','README_ACTIVATION_PACK.md'] as const;

const GENERATED_AT = '2026-06-21T00:00:00.000Z';
const PLAN_MAP: Record<string, { name: string; byokAllowed: boolean }> = { capsule_starter: { name: 'Capsule Starter', byokAllowed: false }, capsule_pro: { name: 'Capsule Pro', byokAllowed: true }, enterprise_managed: { name: 'Enterprise Managed', byokAllowed: true }, transformia_internal: { name: 'TransformIA Internal', byokAllowed: true } };
const SAFE_REF = /^[a-z][a-z0-9_]{2,80}$/;
const sensitivePattern = new RegExp('(@|https?:\\/\\/|\\.\\.\\/|\\/etc\\/|\\b\\d{3}[- .]?\\d{3}[- .]?\\d{3}\\b|\\b\\d{9,}\\b|api[_-]?key|token|secret|password|credential|private[_-]?key|sk_live|pk_live|ghp_|BEGIN' + ' PRIVATE KEY|provider_payload)', 'i');

function canonicalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonicalize); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a],[b]) => a.localeCompare(b)).map(([k,v]) => [k, canonicalize(v)])); return value; }
export function computeStableChecksum(value: unknown): string { return createHash('sha256').update(JSON.stringify(canonicalize(value))).digest('hex'); }
export function computeActivationPackFingerprint(pack: SaaSActivationPack): string { const { fingerprint, validationReport, ...rest } = pack; return computeStableChecksum({ ...rest, validationReport: { ...validationReport, checksum: undefined } }); }

export function buildCaseZeroActivationIntentFixture(): ActivationIntent { return buildDefaultSaaSActivationIntent({ intentId: 'intent_case_zero_v09_l01', source: 'public_website', sourceRoute: 'capsule_demo', locale: 'es-ES', regionId: 'es_eu', operatingPath: 'starter_cloud', selectedPlanCode: 'capsule_starter', trialRequested: true, requestedTemplate: 'portal_vivo', businessKind: 'transformia_case_zero', organizationDraftRef: 'orgdraft_transformia_case_zero', workspaceDraftRef: 'workspacedraft_transformia_case_zero', contactRef: 'contactref_case_zero_public', notesPublicSafe: 'Public-safe case zero activation handoff fixture. No raw contact data, credentials or provider payloads.' }); }
export function buildDefaultSaaSActivationIntent(input: Partial<ActivationIntent>): ActivationIntent { return { intentId: 'intent_public_v09_l01', source: 'public_website', sourceRoute: 'diagnostico', requestedAt: GENERATED_AT, locale: 'es-ES', regionId: 'es_eu', operatingPath: 'starter_cloud', selectedPlanCode: 'capsule_starter', trialRequested: true, requestedTemplate: 'capsule', businessKind: 'generic_public_activation', organizationDraftRef: 'orgdraft_public_activation', workspaceDraftRef: 'workspacedraft_public_activation', contactRef: 'contactref_public_activation', notesPublicSafe: 'Public-safe activation intent only.', publicSafe: true, ...input, publicSafe: true }; }
export function validateActivationIntent(intent: ActivationIntent): ValidationReport { const blockers: string[] = []; const warnings: string[] = []; if (!intent || intent.publicSafe !== true) blockers.push('activation_intent_must_be_public_safe'); if (!ALLOWED_ACTIVATION_ROUTES.includes(intent?.sourceRoute as ActivationIntentRoute)) blockers.push('blocked_invalid_scope'); if (QUARANTINED_WEB_ROUTES.includes((intent?.sourceRoute as string) as never)) blockers.push('blocked_quarantined_route'); if (!(intent?.selectedPlanCode in PLAN_MAP)) blockers.push('blocked_unsupported_plan'); if (intent?.regionId === 'other_review_required') blockers.push('blocked_region_assumption'); for (const field of ['intentId','organizationDraftRef','workspaceDraftRef','contactRef'] as const) { const value = intent?.[field] ?? ''; if (!SAFE_REF.test(value) || sensitivePattern.test(value)) blockers.push(`blocked_sensitive_input:${field}`); } for (const field of ['notesPublicSafe','businessKind','requestedTemplate','locale'] as const) if (sensitivePattern.test(String(intent?.[field] ?? ''))) blockers.push(`blocked_sensitive_input:${field}`); if (intent?.trialRequested) warnings.push('trial_intent_requires_commercial_review'); return { ok: blockers.length === 0, status: blockers.length ? (blockers.includes('blocked_quarantined_route') ? 'blocked_quarantined_route' : blockers.some((b) => b.includes('blocked_sensitive_input')) ? 'blocked_sensitive_input' : 'validation_failed') : 'review_required', blockers, warnings, checkedInvariants: ['public_web_is_not_runtime_authority','canonical_plan_mapping_required','human_review_required','no_secrets','no_live_execution','region_posture_preserved'], generatedFiles: buildActivationPackFileManifest(), checksum: computeStableChecksum({ blockers, warnings, route: intent?.sourceRoute, plan: intent?.selectedPlanCode, region: intent?.regionId }), publicSafe: true }; }
export function buildOrganizationWorkspaceDraft(intent: ActivationIntent): OrganizationWorkspaceDraft { return { organizationDraftId: intent.organizationDraftRef, workspaceDraftId: intent.workspaceDraftRef, organizationDisplayName: `Draft organization for ${intent.businessKind}`, workspaceDisplayName: `Draft workspace for ${intent.requestedTemplate}`, workspaceKind: intent.requestedTemplate, locale: intent.locale, regionId: intent.regionId, publicSafe: true }; }
export function buildPlanTrialDraft(intent: ActivationIntent): PlanTrialDraft { const plan = PLAN_MAP[intent.selectedPlanCode] ?? PLAN_MAP.capsule_starter; return { planCode: intent.selectedPlanCode, planDisplayName: plan.name, trialRequested: intent.trialRequested, trialState: intent.trialRequested ? 'trial_review_required' : 'not_requested', commercialReviewRequired: true, automaticPurchaseFlow: false, instantProvisioning: false, publicSafe: true }; }
export function buildByokReadinessDraft(intent: ActivationIntent): ByokReadinessDraft { const byokRequested = intent.operatingPath === 'local_byok' || intent.operatingPath === 'enterprise_managed'; const plan = PLAN_MAP[intent.selectedPlanCode]; return { byokRequested, providerKinds: byokRequested ? ['operator_review_reference_only'] : [], secretMaterialIncluded: false, readinessStatus: !byokRequested ? 'not_requested' : !plan?.byokAllowed ? 'blocked_plan_not_allowed' : 'requested_review_required', publicSafe: true }; }
export function buildCommissioningChecklist(intent: ActivationIntent, drafts = { planTrialDraft: buildPlanTrialDraft(intent), byokReadinessDraft: buildByokReadinessDraft(intent) }): CommissioningChecklistItem[] { return [{ itemId: 'human_review_required', label: 'Dani/operator review must approve before commissioning.', status: 'pending', blocker: true, evidenceRef: 'operator_review_not_captured', owner: 'transformia_operator', publicSafe: true }, { itemId: 'runtime_authority_required', label: 'Runtime must validate organizations, workspace, entitlements and governance.', status: 'pending', blocker: true, evidenceRef: 'runtime_b01_b05_required', owner: 'runtime', publicSafe: true }, { itemId: 'web_intent_is_display_only', label: 'Public web intent is conversion context only, not authority.', status: 'passed', blocker: false, evidenceRef: intent.sourceRoute, owner: 'web', publicSafe: true }, { itemId: 'trial_is_not_purchase', label: 'Trial request requires commercial review and never creates instant provisioning.', status: drafts.planTrialDraft.trialRequested ? 'pending' : 'not_applicable', blocker: drafts.planTrialDraft.trialRequested, evidenceRef: drafts.planTrialDraft.trialState, owner: 'transformia_operator', publicSafe: true }, { itemId: 'byok_no_secret_material', label: 'BYOK posture is reference-only and contains no secret material.', status: drafts.byokReadinessDraft.readinessStatus.startsWith('blocked') ? 'blocked' : 'passed', blocker: drafts.byokReadinessDraft.readinessStatus.startsWith('blocked'), evidenceRef: drafts.byokReadinessDraft.readinessStatus, owner: 'launcher', publicSafe: true }, { itemId: 'region_locale_review', label: 'Region and locale posture preserved for operator review.', status: intent.regionId === 'other_review_required' ? 'blocked' : 'passed', blocker: intent.regionId === 'other_review_required', evidenceRef: intent.regionId, owner: 'launcher', publicSafe: true }]; }
export function toPublicSaaSActivationPackSummary(pack: SaaSActivationPack): Record<string, unknown> { return { activationPackId: pack.activationPackId, status: pack.validationReport.status, sourceRoute: pack.intent.sourceRoute, operatingPath: pack.intent.operatingPath, planCode: pack.planTrialDraft.planCode, trialState: pack.planTrialDraft.trialState, byokReadinessStatus: pack.byokReadinessDraft.readinessStatus, locale: pack.intent.locale, regionId: pack.intent.regionId, template: pack.intent.requestedTemplate, humanReviewRequired: true, readyForCommissioning: pack.readyForCommissioning, readyForGoLive: false, nextSteps: ['customer_confirms_public_safe_draft','operator_reviews_activation_pack','runtime_validates_authority_before_any_live_action'], publicSafe: true }; }
export function buildSaaSActivationPack(intent: ActivationIntent): SaaSActivationPack { const organizationWorkspaceDraft = buildOrganizationWorkspaceDraft(intent); const planTrialDraft = buildPlanTrialDraft(intent); const byokReadinessDraft = buildByokReadinessDraft(intent); const commissioningChecklist = buildCommissioningChecklist(intent, { planTrialDraft, byokReadinessDraft }); const intentReport = validateActivationIntent(intent); const readyForCommissioning = intentReport.ok && commissioningChecklist.every((i) => !i.blocker && i.status !== 'blocked'); let pack = { activationPackId: `activation_pack_${intent.intentId}`, intent, organizationWorkspaceDraft, planTrialDraft, byokReadinessDraft, commissioningChecklist, humanReviewRequired: true, readyForCommissioning, readyForGoLive: false, publicSafeSummary: {}, validationReport: intentReport, fingerprint: '', generatedAt: GENERATED_AT, publicSafe: true } as SaaSActivationPack; pack.publicSafeSummary = toPublicSaaSActivationPackSummary(pack); pack.validationReport = validateSaaSActivationPack(pack); pack.fingerprint = computeActivationPackFingerprint(pack); return pack; }
export function validateSaaSActivationPack(pack: SaaSActivationPack): ValidationReport { const base = validateActivationIntent(pack.intent); const blockers = [...base.blockers]; const warnings = [...base.warnings]; if (pack.humanReviewRequired !== true) blockers.push('blocked_missing_human_review'); if (pack.readyForGoLive !== false) blockers.push('ready_for_go_live_forbidden'); if (pack.planTrialDraft.automaticPurchaseFlow !== false || pack.planTrialDraft.instantProvisioning !== false || pack.planTrialDraft.commercialReviewRequired !== true) blockers.push('trial_or_plan_authority_bypass'); if ((pack.byokReadinessDraft as { secretMaterialIncluded?: boolean }).secretMaterialIncluded !== false) blockers.push('blocked_byok_secret_material'); if (pack.byokReadinessDraft.readinessStatus === 'ready_reference_only' && !PLAN_MAP[pack.planTrialDraft.planCode]?.byokAllowed) blockers.push('blocked_plan_not_allowed'); if (pack.commissioningChecklist.some((i) => i.blocker || i.status === 'blocked') && pack.readyForCommissioning) blockers.push('blocked_checklist_cannot_be_ready'); if (JSON.stringify(pack.publicSafeSummary).match(sensitivePattern)) blockers.push('public_summary_contains_sensitive_input'); const status: ActivationPackStatus = blockers.length ? (blockers.some((b) => b.includes('byok')) ? 'blocked_byok_secret_material' : blockers.some((b) => b.includes('human')) ? 'blocked_missing_human_review' : 'validation_failed') : 'ready_for_operator_review'; return { ok: blockers.length === 0, status, blockers, warnings, checkedInvariants: [...base.checkedInvariants, 'blocked_checklist_prevents_ready','trial_is_not_purchase','fingerprint_covers_safety_fields'], generatedFiles: buildActivationPackFileManifest(), checksum: computeStableChecksum({ blockers, warnings, packSafety: { intent: pack.intent, plan: pack.planTrialDraft, byok: pack.byokReadinessDraft, checklist: pack.commissioningChecklist, readyForGoLive: pack.readyForGoLive } }), publicSafe: true }; }
export function buildV09FreezeCandidateSummary(pack: SaaSActivationPack): FreezeCandidateSummary { return { version: 'v0.9', capability: 'SaaS Activation Pack Handoff', status: pack.validationReport.blockers.length === 0 ? 'freeze_candidate_ready' : 'freeze_blocked', requiredExternalEvidence: ['web_w01_w05','runtime_b01_b05','launcher_l01'], launcherEvidenceRefs: buildActivationPackFileManifest(pack), blockers: pack.validationReport.blockers, warnings: ['final_freeze_requires_post_merge_cross_repo_evidence', ...pack.validationReport.warnings], publicSafe: true }; }
export function buildActivationPackFileManifest(_pack?: SaaSActivationPack): string[] { return [...ACTIVATION_PACK_FILENAMES]; }
